# Generated by Django 3.0.5 on 2023-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=40)),
                ('book_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=40)),
                ('review_date', models.DateField(auto_now=True)),
                ('review_text', models.CharField(max_length=400)),
                ('review_sentument', models.CharField(max_length=400)),
            ],
        ),
    ]
