# Generated by Django 3.0.5 on 2023-01-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baye_tache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='baye_tache.Book'),
        ),
    ]
